### ISSUE TITLE
About 404 page

### ISSUE THREAD

**Issue by ZhangqianStudio** [g-plane/md-ui-for-bs#1]
well,i think the 404 page is a little boring.i think add some picture like this will be more fun.
here's an example
![example.png](https://blog.zc-xl.com/usr/themes/material/img/random/material-6.png)

**Comment by g-plane** [comment]
It is a good idea! In fact, the 404 page I used currently is the default page of this framework and I haven't change anything. I will make a change.

**Comment by g-plane** [comment]
I found two pictures from https://github.com/vuetifyjs/docs
![md1](https://github.com/vuetifyjs/docs/blob/dev/static/doc-images/md.jpg?raw=true)

![md2](https://github.com/vuetifyjs/docs/blob/dev/static/doc-images/md2.jpg?raw=true)

Which one is better?

**Comment by ZhangqianStudio** [comment]
Maybe the second one?

**Comment by g-plane** [comment]
Should we add something on the picture? Or PR is welcomed!

**Comment by ZhangqianStudio** [comment]
such as “你们不要见到风就是雨”？

**Comment by g-plane** [comment]
Seems not relevant to "Not Found".

**Comment by ZhangqianStudio** [comment]
it's just a joke,please don't care.

**Comment by ZhangqianStudio** [comment]
i think "404 not found"is enough
